"""Filesystem and workflow integration scenarios promoted from the legacy suite."""

__version__ = "v361"

import pytest
from tests import _legacy_suite as legacy

pytestmark = pytest.mark.integration

test_existing_volume_reinventory_reuses_existing_token_and_replaces_exact_logs = legacy.test_existing_volume_reinventory_reuses_existing_token_and_replaces_exact_logs
test_v246_add_shows_rename_compliantly_renames_ready_folder_in_place = legacy.test_v246_add_shows_rename_compliantly_renames_ready_folder_in_place
test_v263_prepare_inventory_copy_delete_moves_same_partition_without_mutating_inventory_record = legacy.test_v263_prepare_inventory_copy_delete_moves_same_partition_without_mutating_inventory_record
test_v263_prepare_inventory_copy_delete_copy_verifies_sizes_and_deletes_original = legacy.test_v263_prepare_inventory_copy_delete_copy_verifies_sizes_and_deletes_original
test_v266_inventory_copy_delete_tags_transferred_compliant_folder = legacy.test_v266_inventory_copy_delete_tags_transferred_compliant_folder
test_v286_process_groups_returns_destination_record_for_copy_delete = legacy.test_v286_process_groups_returns_destination_record_for_copy_delete
test_v345_inventory_dry_run_reports_resulting_show_and_planned_tags = legacy.test_v345_inventory_dry_run_reports_resulting_show_and_planned_tags
test_v345_tag_dry_run_simulates_shn_conversion_and_tags_without_writes = legacy.test_v345_tag_dry_run_simulates_shn_conversion_and_tags_without_writes
test_v345_add_shows_dry_run_reports_show_name_and_planned_tags_without_writes = legacy.test_v345_add_shows_dry_run_reports_show_name_and_planned_tags_without_writes
test_v356_wrapper_parts_do_not_promote_parent_when_unrelated_music_sibling_exists = legacy.test_v356_wrapper_parts_do_not_promote_parent_when_unrelated_music_sibling_exists
