__version__ = "v322"
# TLO-GI package version: v322
__version_summary__ = 'Preserves trailing parenthetical show-name suffixes across compliant Add Shows, full inventory rename/tag, and standalone tagging.'
# TLO-GI version summary: Preserves trailing parenthetical show-name suffixes across compliant Add Shows, full inventory rename/tag, and standalone tagging.
import re

US_STATE_CODE_TO_NAME = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "DC": "District of Columbia", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii",
    "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas",
    "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
    "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada",
    "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York",
    "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah",
    "VT": "Vermont", "VA": "Virginia", "WA": "Washington", "WV": "West Virginia",
    "WI": "Wisconsin", "WY": "Wyoming",
}

US_STATE_OLD_ABBREVIATIONS = {
    "ala": "AL",
    "alaska": "AK",
    "ariz": "AZ",
    "ark": "AR",
    "calif": "CA",
    "colo": "CO",
    "conn": "CT",
    "del": "DE",
    "d c": "DC",
    "dc": "DC",
    "fla": "FL",
    "ga": "GA",
    "hawaii": "HI",
    "ida": "ID",
    "idaho": "ID",
    "ill": "IL",
    "ind": "IN",
    "iowa": "IA",
    "kans": "KS",
    "ky": "KY",
    "la": "LA",
    "maine": "ME",
    "md": "MD",
    "mass": "MA",
    "mich": "MI",
    "minn": "MN",
    "miss": "MS",
    "mo": "MO",
    "mont": "MT",
    "nebr": "NE",
    "nev": "NV",
    "n h": "NH",
    "nh": "NH",
    "n j": "NJ",
    "nj": "NJ",
    "n mex": "NM",
    "n m": "NM",
    "nm": "NM",
    "n y": "NY",
    "ny": "NY",
    "n c": "NC",
    "nc": "NC",
    "n dak": "ND",
    "n d": "ND",
    "nd": "ND",
    "ohio": "OH",
    "okla": "OK",
    "oreg": "OR",
    "pa": "PA",
    "penna": "PA",
    "penn": "PA",
    "r i": "RI",
    "ri": "RI",
    "s c": "SC",
    "sc": "SC",
    "s dak": "SD",
    "s d": "SD",
    "sd": "SD",
    "tenn": "TN",
    "tex": "TX",
    "utah": "UT",
    "vt": "VT",
    "va": "VA",
    "wash": "WA",
    "w va": "WV",
    "w virg": "WV",
    "wv": "WV",
    "wis": "WI",
    "wisc": "WI",
    "wyo": "WY",
}

US_STATE_ALIASES = {
    **{name.lower(): code for code, name in US_STATE_CODE_TO_NAME.items()},
    **US_STATE_OLD_ABBREVIATIONS,
}
US_STATE_CODES = tuple(sorted(US_STATE_CODE_TO_NAME.keys()))
US_STATE_FULL_NAMES = tuple(US_STATE_CODE_TO_NAME[code] for code in US_STATE_CODES)
US_STATE_OLD_TERMS = tuple(
    term for term in sorted(set(US_STATE_OLD_ABBREVIATIONS.keys()), key=lambda s: (-len(s), s.lower()))
    if term not in {code.lower() for code in US_STATE_CODES}
)
STATE_SEARCH_TERMS = tuple(list(US_STATE_CODES) + list(US_STATE_FULL_NAMES) + list(US_STATE_OLD_TERMS))

COUNTRY_ALIASES = {
    'albania': 'Albania',
    'andorra': 'Andorra',
    'argentina': 'Argentina',
    'australia': 'Australia',
    'austria': 'Austria',
    'belarus': 'Belarus',
    'belgium': 'Belgium',
    'bolivia': 'Bolivia',
    'bosnia': 'Bosnia',
    'brazil': 'Brazil',
    'bulgaria': 'Bulgaria',
    'canada': 'Canada',
    'chile': 'Chile',
    'china': 'China',
    'colombia': 'Colombia',
    'croatia': 'Croatia',
    'czech republic': 'Czech Republic',
    'denmark': 'Denmark',
    'ecuador': 'Ecuador',
    'egypt': 'Egypt',
    'england': 'England',
    'estonia': 'Estonia',
    'finland': 'Finland',
    'france': 'France',
    'germany': 'Germany',
    'greece': 'Greece',
    'guyana': 'Guyana',
    'herzegovina': 'Herzegovina',
    'hungary': 'Hungary',
    'iceland': 'Iceland',
    'india': 'India',
    'ireland': 'Ireland',
    'italy': 'Italy',
    'jamaica': 'Jamaica',
    'japan': 'Japan',
    'kosovo': 'Kosovo',
    'latvia': 'Latvia',
    'liechtenstein': 'Liechtenstein',
    'lithuania': 'Lithuania',
    'luxembourg': 'Luxembourg',
    'malta': 'Malta',
    'mexico': 'Mexico',
    'moldova': 'Moldova',
    'monaco': 'Monaco',
    'montenegro': 'Montenegro',
    'netherlands': 'Netherlands',
    'new zealand': 'New Zealand',
    'north macedonia': 'North Macedonia',
    'norway': 'Norway',
    'panama': 'Panama',
    'paraguay': 'Paraguay',
    'peru': 'Peru',
    'poland': 'Poland',
    'portugal': 'Portugal',
    'romania': 'Romania',
    'russia': 'Russia',
    'san marino': 'San Marino',
    'serbia': 'Serbia',
    'slovakia': 'Slovakia',
    'slovenia': 'Slovenia',
    'south africa': 'South Africa',
    'spain': 'Spain',
    'singapore': 'Singapore',
    'suriname': 'Suriname',
    'sweden': 'Sweden',
    'switzerland': 'Switzerland',
    'u k': 'UK',
    'u s': 'USA',
    'u s a': 'USA',
    'u.s.': 'USA',
    'u.s.a.': 'USA',
    'uk': 'UK',
    'ukraine': 'Ukraine',
    'united kingdom': 'UK',
    'united states': 'USA',
    'uruguay': 'Uruguay',
    'us': 'USA',
    'usa': 'USA',
    'vatican city': 'Vatican City',
    'venezuela': 'Venezuela',
}
COUNTRY_SEARCH_TERMS = tuple(list(sorted({
    'Albania',
    'Andorra',
    'Argentina',
    'Australia',
    'Austria',
    'Belarus',
    'Belgium',
    'Bolivia',
    'Bosnia',
    'Brazil',
    'Bulgaria',
    'Canada',
    'Chile',
    'Colombia',
    'Croatia',
    'China',
    'Egypt',
    'India',
    'Jamaica',
    'Japan',
    'New Zealand',
    'Singapore',
    'South Africa',
    'Czech Republic',
    'Denmark',
    'Ecuador',
    'England',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Guyana',
    'Herzegovina',
    'Hungary',
    'Iceland',
    'Ireland',
    'Italy',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Mexico',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'North Macedonia',
    'Norway',
    'Panama',
    'Paraguay',
    'Peru',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'San Marino',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Ukraine',
    'United Kingdom',
    'UK',
    'United States',
    'US',
    'U.S.',
    'U.S.A.',
    'Uruguay',
    'Vatican City',
    'Venezuela',
    'USA',
    'U S A',
    'U S',
    'U K',
}, key=lambda s: (-len(s), s.lower()))))

CITY_PREFIX_WORDS = frozenset({
    "new", "north", "south", "east", "west", "los", "las", "san", "santa", "saint", "st",
    "old", "upper", "lower", "fort", "ft", "mount", "mt", "port", "lake", "el", "la",
})

AMBIGUOUS_STATE_CODES = frozenset({"IN", "HI", "OR", "MA", "OK", "OH"})
LOWERCASE_COMMON_STATE_CODES = frozenset({"IN", "HI", "OR", "MA", "OK", "OH", "ME", "ID", "PA", "LA", "MO", "CO", "DE"})
LOWERCASE_STATE_NOISE_WORDS = frozenset({
    "a", "all", "am", "an", "and", "any", "are", "as", "at", "be", "believe", "by", "for", "from",
    "go", "if", "in", "into", "is", "it", "live", "me", "my", "of", "on", "or", "part", "set",
    "soul", "the", "to", "track", "up", "with", "you", "your",
})
LOCATION_MAX_LEN = 45
HEADER_MAX_LINES = 10
ARTIST_HEADER_LINE_LIMIT = 2
VENUE_HEADER_LINE_LIMIT = 4

MONTHS = {
    "jan": 1, "january": 1, "feb": 2, "february": 2, "mar": 3, "march": 3,
    "apr": 4, "april": 4, "may": 5, "jun": 6, "june": 6, "jul": 7, "july": 7,
    "aug": 8, "august": 8, "sep": 9, "sept": 9, "september": 9, "oct": 10,
    "october": 10, "nov": 11, "november": 11, "dec": 12, "december": 12,
}
MONTH_NAME_PATTERN = r"jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t)?(?:ember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?"
MONTH_NAME_WORDS = tuple(sorted(MONTHS.keys(), key=lambda value: (-len(value), value)))


def _case_constrained_words_pattern(words):
    """Return a regex alternation allowing lower, UPPER, or Title case only."""
    values = []
    for word in words:
        values.extend({word.lower(), word.upper(), word.capitalize()})
    return r"(?:" + "|".join(re.escape(value) for value in sorted(values, key=lambda value: (-len(value), value))) + r")"


MONTH_NAME_CASED_PATTERN = _case_constrained_words_pattern(MONTH_NAME_WORDS)
ORDINAL_SUFFIX = r"(?:st|nd|rd|th|ST|ND|RD|TH)?"

QUALIFIER_PATTERNS = (
    (re.compile(r"\bset\s*1\b|\bset\s*one\b|\b1st\s*set\b", re.IGNORECASE), "Set 1"),
    (re.compile(r"\bset\s*2\b|\bset\s*two\b|\b2nd\s*set\b", re.IGNORECASE), "Set 2"),
    (re.compile(r"\bset\s*3\b|\bset\s*three\b|\b3rd\s*set\b", re.IGNORECASE), "Set 3"),
    (re.compile(r"\bearly\b", re.IGNORECASE), "Early Show"),
    (re.compile(r"\blate\b", re.IGNORECASE), "Late Show"),
    (re.compile(r"\bafternoon\b", re.IGNORECASE), "Afternoon Show"),
    (re.compile(r"\bevening\b", re.IGNORECASE), "Evening Show"),
    (re.compile(r"\bacoustic\b", re.IGNORECASE), "Acoustic Set"),
    (re.compile(r"\belectric\b", re.IGNORECASE), "Electric Set"),
    (re.compile(r"\bmatinee\b", re.IGNORECASE), "Matinee"),
    (re.compile(r"\bsoundcheck\b", re.IGNORECASE), "Soundcheck"),
    (re.compile(r"\brehearsal\b", re.IGNORECASE), "Rehearsal"),
)

BIT24_PATTERNS = (
    re.compile(r"\b24\s*[-_/ ]?bit\b", re.IGNORECASE),
    re.compile(r"\b24[-_/ ](44|48|88(?:\.2)?|96|176(?:\.4)?|192)\b", re.IGNORECASE),
    re.compile(r"\b24[-_/ ]?(96|192)k?\b", re.IGNORECASE),
)

SETLIST_LINE_FILTERS = (
    re.compile(r"^\s*\d{1,2}[.) -]+\s*\S+"),
    re.compile(r"^\s*d\d+t\d+", re.IGNORECASE),
    re.compile(r"\bset\s*1\b|\bset\s*2\b|\bencore\b", re.IGNORECASE),
)
